# Generated by Django 5.0.6 on 2024-06-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_publication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
